---
- name: Triage Down Interfaces 
  hosts: rtr1
  gather_facts: False
  tasks:
  
  - name: debug 
    ansible.builtin.debug:
      msg :
      - "{{ summary }}"
      - "{{ message }}"

  - name: set fact for Tunnel0
    set_fact:
      interface: Tunnel0
    when: 
    - '"tu0" in summary'

  - name: Attempt a No shut for {{ inventory_hostname }} {{ interface }}
    cisco.ios.ios_interfaces:
      config:
      - name: "{{ interface }}"
        enabled: True
   
  - name: Check Interface State for {{ inventory_hostname }} {{ interface }}
    cisco.ios.command:
      commands: show ip interface brief
    register: int_state

  - name: Print Event Info
    ansible.builtin.debug:
      var: int_state.stdout_lines[0]

    



      