---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool!"
     
      action:
        #run_job_template:
        #  name: "Solarwinds-Fix-Ports"
        #  organization: "Default"
        #  job_args:
        #    extra_vars:
        #      summary: "{{ event.payload.summary }}"
        #      message: "{{ event.payload.message }}"
        run_playbook:
          name: say-what.yml

